version: '3'

tasks:
  dev:
    cmd: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  auth:
    cmd: python -m scripts.auth_mf

  lint:
    cmds:
      - ruff check . --fix
      - ruff format .